# Generated by Django 5.1.7 on 2025-12-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_saas_organization'),
        ('users', '0005_user_add_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='For detailed staff assignment (e.g. Cardiology)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.hospital', verbose_name='Hospital'),
        ),
    ]
