# Generated by Django 5.1.7 on 2025-12-06 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aiconfiguration_aiprompttemplate_aiconversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('account_locked', 'Account Locked'), ('suspicious_activity', 'Suspicious Activity'), ('data_access', 'Data Access'), ('admin_action', 'Admin Action')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', '-timestamp'], name='core_securi_event_t_7b6ea0_idx'), models.Index(fields=['user', '-timestamp'], name='core_securi_user_id_048e82_idx'), models.Index(fields=['ip_address', '-timestamp'], name='core_securi_ip_addr_b078f3_idx')],
            },
        ),
    ]
