# Generated by Django 5.1.7 on 2025-12-08 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_enterprise_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Hospital Name')),
                ('slug', models.SlugField(help_text='Unique identifier for URL routing (e.g., st-marys-hospital)', max_length=200, unique=True)),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#0d6efd', help_text='Hex color code (e.g., #0d6efd)', max_length=7, verbose_name='Primary Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic (Small Clinic)'), ('standard', 'Standard (Medium Hospital)'), ('enterprise', 'Enterprise (Multi-Specialty)')], default='standard', max_length=50, verbose_name='Subscription Plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('head_of_department', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Head of Department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='core.hospital', verbose_name='Hospital')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
                'unique_together': {('hospital', 'name')},
            },
        ),
    ]
