# Generated by Django 5.1.7 on 2025-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_telemedicine',
            field=models.BooleanField(default=False, help_text='Enable video consultation for this appointment', verbose_name='Telemedicine Appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='jitsi_room_name',
            field=models.CharField(blank=True, help_text='Unique room name for video consultation', max_length=100, null=True, verbose_name='Jitsi Room Name'),
        ),
    ]
